name: neural-ecology
channels:
  - pytorch
  - conda-forge
dependencies:
  - jupyterlab
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - python>=3.6
  - pip
  - tqdm
  - pytorch
  - torchvision
  - cudatoolkit=10.0
  - pip:
      - pyro-ppl